# Generated by Django 3.0.6 on 2020-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='mes_range',
        ),
        migrations.AddField(
            model_name='sensor',
            name='range_max',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='sensor',
            name='range_min',
            field=models.FloatField(default=0),
        ),
    ]
