# Generated by Django 3.0.6 on 2020-05-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20200527_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='graphs.Sensor'),
        ),
    ]
